### PR TITLE
Revising Monotone Least Squares as python notebook

### PR DESCRIPTION
**Pull request by rubiop**
Draft PR with `.ipynb` file

### CODE REVIEW

**Comment by bonh** [comment]
Hi @rubiop! I guess that you coded the notebook in google colab, saved the notebook as a *.ipynb file and transformed into the python file via jupytext. Is that correct?

**Comment by rubiop** [comment]
> Hi @rubiop! I guess that you coded the notebook in google colab, saved the notebook as a *.ipynb file and transformed into the python file via jupytext. Is that correct?

@bonh That's absolutely correct... I saw that there was a bunch of specifications that remains after the jupytext transformation, I was hoping this won't be an issue. Is it? Do you know if there is way to clean that? I use `jupytext --to py mynotebook.ipynb` to transform my notebook, maybe there is some other option to specify.

**Comment by bonh** [comment]
I am working on it and will hopefully come up with a nice solution...

**Review by bonh — APPROVED** [review]
Looks good!

**Pull request merged**
